/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */

export type AgentCreateRequestApiVersion = typeof AgentCreateRequestApiVersion[keyof typeof AgentCreateRequestApiVersion];


export const AgentCreateRequestApiVersion = {
  'komikagentjob\/v1': 'komikagentjob\/v1',
} as const;
