/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */
import type { AgentCreateRequestParameter } from './agentCreateRequestParameter';

export interface AgentCreateRequest {
  name: string;
  description: string;
  endpoint: string;
  capabilities: string[];
  parameters: AgentCreateRequestParameter[];
  tags?: string[];
}
