/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */

export type AgentCreateResponseStatus = typeof AgentCreateResponseStatus[keyof typeof AgentCreateResponseStatus];


export const AgentCreateResponseStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
