/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */
import type { AgentCreateRequestAnnotationsItem } from './agentCreateRequestAnnotationsItem';
import type { AgentCreateRequestEnvItem } from './agentCreateRequestEnvItem';
import type { AgentCreateRequestResources } from './agentCreateRequestResources';
import type { AgentCreateRequestSecretsItem } from './agentCreateRequestSecretsItem';

export interface AgentCreateRequest {
  name: string;
  description?: string;
  image: string;
  imagePullSecret?: string;
  resources?: AgentCreateRequestResources;
  env?: AgentCreateRequestEnvItem[];
  secrets?: AgentCreateRequestSecretsItem[];
  annotations?: AgentCreateRequestAnnotationsItem[];
}
