/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */
import type { AuditlogGetResponseMetadata } from './auditlogGetResponseMetadata';
import type { AuditlogResponse } from './auditlogResponse';

export interface AuditlogGetResponse {
  metadata?: AuditlogGetResponseMetadata;
  items?: AuditlogResponse[];
}
