/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */
import type { AgentCreateRequest } from './agentCreateRequest';
import type { AgentModel } from './agentModel';

export type DetailedAgentModel = AgentModel & AgentCreateRequest;
