/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */
import type { HookRegisterRequest } from './hookRegisterRequest';

export type HookregisterResponse = HookRegisterRequest & {
  /** The id of the hook. */
  id?: string;
  /** The secret key to send with the hook. */
  secretKey?: string;
  /** The creation time of the hook. */
  createdAt?: string;
  /** The update time of the hook. */
  updatedAt?: string;
};
