/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */

export type HookRegisterRequestType = typeof HookRegisterRequestType[keyof typeof HookRegisterRequestType];


export const HookRegisterRequestType = {
  customhook: 'custom.hook',
} as const;
