/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */

export interface SlackEventRequest {
  type: string;
  challenge: string;
  token: string;
}
