/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminCreateRequest,
  AdminGetResponse,
  ErrorResponse
} from './schemas';

export type getAdminResponse200 = {
  data: AdminGetResponse
  status: 200
}

export type getAdminResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAdminResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAdminResponseSuccess = (getAdminResponse200) & {
  headers: Headers;
};
export type getAdminResponseError = (getAdminResponse404 | getAdminResponse500) & {
  headers: Headers;
};

export type getAdminResponse = (getAdminResponseSuccess | getAdminResponseError)

export const getGetAdminUrl = () => {




  return `http://localhost:65080/api/v1/admin`
}

export const getAdmin = async ( options?: RequestInit): Promise<getAdminResponse> => {

  const res = await fetch(getGetAdminUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAdminResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAdminResponse
}





export const getGetAdminQueryKey = () => {
    return [
    `http://localhost:65080/api/v1/admin`
    ] as const;
    }


export const getGetAdminQueryOptions = <TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdmin>>> = ({ signal }) => getAdmin({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminQueryResult = NonNullable<Awaited<ReturnType<typeof getAdmin>>>
export type GetAdminQueryError = ErrorResponse


export function useGetAdmin<TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdmin>>,
          TError,
          Awaited<ReturnType<typeof getAdmin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdmin<TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdmin>>,
          TError,
          Awaited<ReturnType<typeof getAdmin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdmin<TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAdmin<TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type postAdminResponse201 = {
  data: void
  status: 201
}

export type postAdminResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postAdminResponseSuccess = (postAdminResponse201) & {
  headers: Headers;
};
export type postAdminResponseError = (postAdminResponse500) & {
  headers: Headers;
};

export type postAdminResponse = (postAdminResponseSuccess | postAdminResponseError)

export const getPostAdminUrl = () => {




  return `http://localhost:65080/api/v1/admin`
}

export const postAdmin = async (adminCreateRequest: AdminCreateRequest, options?: RequestInit): Promise<postAdminResponse> => {

  const res = await fetch(getPostAdminUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminCreateRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAdminResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postAdminResponse
}




export const getPostAdminMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdmin>>, TError,{data: AdminCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postAdmin>>, TError,{data: AdminCreateRequest}, TContext> => {

const mutationKey = ['postAdmin'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdmin>>, {data: AdminCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAdmin(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminMutationResult = NonNullable<Awaited<ReturnType<typeof postAdmin>>>
    export type PostAdminMutationBody = AdminCreateRequest
    export type PostAdminMutationError = ErrorResponse

    export const usePostAdmin = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdmin>>, TError,{data: AdminCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdmin>>,
        TError,
        {data: AdminCreateRequest},
        TContext
      > => {
      return useMutation(getPostAdminMutationOptions(options), queryClient);
    }
