/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * API Contracts for Komik
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminCreateRequest,
  AdminGetResponse,
  AgentCreateRequest,
  AgentCreateResponse,
  AgentGetResponse,
  AuditlogGetResponse,
  ChannelGetResponse,
  ChannelRequest,
  ChannelResponse,
  DetailedAgentModel,
  ErrorResponse,
  GetAuditlogParams,
  GetAuthOidcCallbackParams,
  HookRegisterRequest,
  HookRegisteredList,
  HookSendRequest,
  HookregisterResponse,
  PostHookSlackBody,
  UserResponse
} from './schemas';

import { customInstance } from './httpClient';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postChannelChannelIdSendResponse201 = {
  data: void
  status: 201
}

export type postChannelChannelIdSendResponseSuccess = (postChannelChannelIdSendResponse201) & {
  headers: Headers;
};
;

export type postChannelChannelIdSendResponse = (postChannelChannelIdSendResponseSuccess)

export const getPostChannelChannelIdSendUrl = (channelId: string,) => {




  return `http://localhost:65080/api/v1/channel/${channelId}/send`
}

export const postChannelChannelIdSend = async (channelId: string, options?: RequestInit): Promise<postChannelChannelIdSendResponse> => {

  return customInstance<postChannelChannelIdSendResponse>(getPostChannelChannelIdSendUrl(channelId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostChannelChannelIdSendMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannelChannelIdSend>>, TError,{channelId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postChannelChannelIdSend>>, TError,{channelId: string}, TContext> => {

const mutationKey = ['postChannelChannelIdSend'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChannelChannelIdSend>>, {channelId: string}> = (props) => {
          const {channelId} = props ?? {};

          return  postChannelChannelIdSend(channelId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostChannelChannelIdSendMutationResult = NonNullable<Awaited<ReturnType<typeof postChannelChannelIdSend>>>

    export type PostChannelChannelIdSendMutationError = unknown

    export const usePostChannelChannelIdSend = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannelChannelIdSend>>, TError,{channelId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postChannelChannelIdSend>>,
        TError,
        {channelId: string},
        TContext
      > => {
      return useMutation(getPostChannelChannelIdSendMutationOptions(options), queryClient);
    }

export type getChannelResponse200 = {
  data: ChannelGetResponse
  status: 200
}

export type getChannelResponseSuccess = (getChannelResponse200) & {
  headers: Headers;
};
;

export type getChannelResponse = (getChannelResponseSuccess)

export const getGetChannelUrl = () => {




  return `http://localhost:65080/api/v1/channel`
}

export const getChannel = async ( options?: RequestInit): Promise<getChannelResponse> => {

  return customInstance<getChannelResponse>(getGetChannelUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetChannelQueryKey = () => {
    return [
    `http://localhost:65080/api/v1/channel`
    ] as const;
    }


export const getGetChannelQueryOptions = <TData = Awaited<ReturnType<typeof getChannel>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannel>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChannelQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChannel>>> = ({ signal }) => getChannel({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChannel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChannelQueryResult = NonNullable<Awaited<ReturnType<typeof getChannel>>>
export type GetChannelQueryError = unknown


export function useGetChannel<TData = Awaited<ReturnType<typeof getChannel>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannel>>,
          TError,
          Awaited<ReturnType<typeof getChannel>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChannel<TData = Awaited<ReturnType<typeof getChannel>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannel>>,
          TError,
          Awaited<ReturnType<typeof getChannel>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChannel<TData = Awaited<ReturnType<typeof getChannel>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannel>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetChannel<TData = Awaited<ReturnType<typeof getChannel>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannel>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChannelQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type postChannelResponse200 = {
  data: ChannelResponse
  status: 200
}

export type postChannelResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postChannelResponseSuccess = (postChannelResponse200) & {
  headers: Headers;
};
export type postChannelResponseError = (postChannelResponse500) & {
  headers: Headers;
};

export type postChannelResponse = (postChannelResponseSuccess | postChannelResponseError)

export const getPostChannelUrl = () => {




  return `http://localhost:65080/api/v1/channel`
}

export const postChannel = async (channelRequest: ChannelRequest, options?: RequestInit): Promise<postChannelResponse> => {

  return customInstance<postChannelResponse>(getPostChannelUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(channelRequest)
  }
);}




export const getPostChannelMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannel>>, TError,{data: ChannelRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postChannel>>, TError,{data: ChannelRequest}, TContext> => {

const mutationKey = ['postChannel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChannel>>, {data: ChannelRequest}> = (props) => {
          const {data} = props ?? {};

          return  postChannel(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostChannelMutationResult = NonNullable<Awaited<ReturnType<typeof postChannel>>>
    export type PostChannelMutationBody = ChannelRequest
    export type PostChannelMutationError = ErrorResponse

    export const usePostChannel = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannel>>, TError,{data: ChannelRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postChannel>>,
        TError,
        {data: ChannelRequest},
        TContext
      > => {
      return useMutation(getPostChannelMutationOptions(options), queryClient);
    }

export type getAgentIdResponse200 = {
  data: DetailedAgentModel
  status: 200
}

export type getAgentIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAgentIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAgentIdResponseSuccess = (getAgentIdResponse200) & {
  headers: Headers;
};
export type getAgentIdResponseError = (getAgentIdResponse404 | getAgentIdResponse500) & {
  headers: Headers;
};

export type getAgentIdResponse = (getAgentIdResponseSuccess | getAgentIdResponseError)

export const getGetAgentIdUrl = (id: string,) => {




  return `http://localhost:65080/api/v1/agent/${id}`
}

export const getAgentId = async (id: string, options?: RequestInit): Promise<getAgentIdResponse> => {

  return customInstance<getAgentIdResponse>(getGetAgentIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAgentIdQueryKey = (id: string,) => {
    return [
    `http://localhost:65080/api/v1/agent/${id}`
    ] as const;
    }


export const getGetAgentIdQueryOptions = <TData = Awaited<ReturnType<typeof getAgentId>>, TError = ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgentId>>> = ({ signal }) => getAgentId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAgentId>>>
export type GetAgentIdQueryError = ErrorResponse


export function useGetAgentId<TData = Awaited<ReturnType<typeof getAgentId>>, TError = ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentId>>,
          TError,
          Awaited<ReturnType<typeof getAgentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentId<TData = Awaited<ReturnType<typeof getAgentId>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentId>>,
          TError,
          Awaited<ReturnType<typeof getAgentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentId<TData = Awaited<ReturnType<typeof getAgentId>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAgentId<TData = Awaited<ReturnType<typeof getAgentId>>, TError = ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getAgentResponse200 = {
  data: AgentGetResponse
  status: 200
}

export type getAgentResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAgentResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAgentResponseSuccess = (getAgentResponse200) & {
  headers: Headers;
};
export type getAgentResponseError = (getAgentResponse404 | getAgentResponse500) & {
  headers: Headers;
};

export type getAgentResponse = (getAgentResponseSuccess | getAgentResponseError)

export const getGetAgentUrl = () => {




  return `http://localhost:65080/api/v1/agent`
}

export const getAgent = async ( options?: RequestInit): Promise<getAgentResponse> => {

  return customInstance<getAgentResponse>(getGetAgentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAgentQueryKey = () => {
    return [
    `http://localhost:65080/api/v1/agent`
    ] as const;
    }


export const getGetAgentQueryOptions = <TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgent>>> = ({ signal }) => getAgent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentQueryResult = NonNullable<Awaited<ReturnType<typeof getAgent>>>
export type GetAgentQueryError = ErrorResponse


export function useGetAgent<TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgent>>,
          TError,
          Awaited<ReturnType<typeof getAgent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgent<TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgent>>,
          TError,
          Awaited<ReturnType<typeof getAgent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgent<TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAgent<TData = Awaited<ReturnType<typeof getAgent>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type postAgentResponse200 = {
  data: AgentCreateResponse
  status: 200
}

export type postAgentResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postAgentResponseSuccess = (postAgentResponse200) & {
  headers: Headers;
};
export type postAgentResponseError = (postAgentResponse500) & {
  headers: Headers;
};

export type postAgentResponse = (postAgentResponseSuccess | postAgentResponseError)

export const getPostAgentUrl = () => {




  return `http://localhost:65080/api/v1/agent`
}

export const postAgent = async (agentCreateRequest: AgentCreateRequest, options?: RequestInit): Promise<postAgentResponse> => {

  return customInstance<postAgentResponse>(getPostAgentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(agentCreateRequest)
  }
);}




export const getPostAgentMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAgent>>, TError,{data: AgentCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAgent>>, TError,{data: AgentCreateRequest}, TContext> => {

const mutationKey = ['postAgent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAgent>>, {data: AgentCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAgent(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAgentMutationResult = NonNullable<Awaited<ReturnType<typeof postAgent>>>
    export type PostAgentMutationBody = AgentCreateRequest
    export type PostAgentMutationError = ErrorResponse

    export const usePostAgent = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAgent>>, TError,{data: AgentCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAgent>>,
        TError,
        {data: AgentCreateRequest},
        TContext
      > => {
      return useMutation(getPostAgentMutationOptions(options), queryClient);
    }

export type getHookResponse200 = {
  data: HookRegisteredList
  status: 200
}

export type getHookResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getHookResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getHookResponseSuccess = (getHookResponse200) & {
  headers: Headers;
};
export type getHookResponseError = (getHookResponse404 | getHookResponse500) & {
  headers: Headers;
};

export type getHookResponse = (getHookResponseSuccess | getHookResponseError)

export const getGetHookUrl = () => {




  return `http://localhost:65080/api/v1/hook`
}

export const getHook = async ( options?: RequestInit): Promise<getHookResponse> => {

  return customInstance<getHookResponse>(getGetHookUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHookQueryKey = () => {
    return [
    `http://localhost:65080/api/v1/hook`
    ] as const;
    }


export const getGetHookQueryOptions = <TData = Awaited<ReturnType<typeof getHook>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHookQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHook>>> = ({ signal }) => getHook({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHook>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHookQueryResult = NonNullable<Awaited<ReturnType<typeof getHook>>>
export type GetHookQueryError = ErrorResponse


export function useGetHook<TData = Awaited<ReturnType<typeof getHook>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHook>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHook>>,
          TError,
          Awaited<ReturnType<typeof getHook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHook<TData = Awaited<ReturnType<typeof getHook>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHook>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHook>>,
          TError,
          Awaited<ReturnType<typeof getHook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHook<TData = Awaited<ReturnType<typeof getHook>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHook<TData = Awaited<ReturnType<typeof getHook>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHookQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type postHookResponse200 = {
  data: HookregisterResponse
  status: 200
}

export type postHookResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postHookResponseSuccess = (postHookResponse200) & {
  headers: Headers;
};
export type postHookResponseError = (postHookResponse500) & {
  headers: Headers;
};

export type postHookResponse = (postHookResponseSuccess | postHookResponseError)

export const getPostHookUrl = () => {




  return `http://localhost:65080/api/v1/hook`
}

export const postHook = async (hookRegisterRequest: HookRegisterRequest, options?: RequestInit): Promise<postHookResponse> => {

  return customInstance<postHookResponse>(getPostHookUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(hookRegisterRequest)
  }
);}




export const getPostHookMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postHook>>, TError,{data: HookRegisterRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postHook>>, TError,{data: HookRegisterRequest}, TContext> => {

const mutationKey = ['postHook'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postHook>>, {data: HookRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postHook(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostHookMutationResult = NonNullable<Awaited<ReturnType<typeof postHook>>>
    export type PostHookMutationBody = HookRegisterRequest
    export type PostHookMutationError = ErrorResponse

    export const usePostHook = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postHook>>, TError,{data: HookRegisterRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postHook>>,
        TError,
        {data: HookRegisterRequest},
        TContext
      > => {
      return useMutation(getPostHookMutationOptions(options), queryClient);
    }

export type postHookIdResponse200 = {
  data: string
  status: 200
}

export type postHookIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postHookIdResponseSuccess = (postHookIdResponse200) & {
  headers: Headers;
};
export type postHookIdResponseError = (postHookIdResponse500) & {
  headers: Headers;
};

export type postHookIdResponse = (postHookIdResponseSuccess | postHookIdResponseError)

export const getPostHookIdUrl = (id: string,) => {




  return `http://localhost:65080/api/v1/hook/${id}`
}

export const postHookId = async (id: string,
    hookSendRequest: HookSendRequest, options?: RequestInit): Promise<postHookIdResponse> => {

  return customInstance<postHookIdResponse>(getPostHookIdUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(hookSendRequest)
  }
);}




export const getPostHookIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postHookId>>, TError,{id: string;data: HookSendRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postHookId>>, TError,{id: string;data: HookSendRequest}, TContext> => {

const mutationKey = ['postHookId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postHookId>>, {id: string;data: HookSendRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postHookId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostHookIdMutationResult = NonNullable<Awaited<ReturnType<typeof postHookId>>>
    export type PostHookIdMutationBody = HookSendRequest
    export type PostHookIdMutationError = ErrorResponse

    export const usePostHookId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postHookId>>, TError,{id: string;data: HookSendRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postHookId>>,
        TError,
        {id: string;data: HookSendRequest},
        TContext
      > => {
      return useMutation(getPostHookIdMutationOptions(options), queryClient);
    }

export type postHookSlackResponse200 = {
  data: string
  status: 200
}

export type postHookSlackResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postHookSlackResponseSuccess = (postHookSlackResponse200) & {
  headers: Headers;
};
export type postHookSlackResponseError = (postHookSlackResponse500) & {
  headers: Headers;
};

export type postHookSlackResponse = (postHookSlackResponseSuccess | postHookSlackResponseError)

export const getPostHookSlackUrl = () => {




  return `http://localhost:65080/api/v1/hook/slack`
}

export const postHookSlack = async (postHookSlackBody: PostHookSlackBody, options?: RequestInit): Promise<postHookSlackResponse> => {

  return customInstance<postHookSlackResponse>(getPostHookSlackUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postHookSlackBody)
  }
);}




export const getPostHookSlackMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postHookSlack>>, TError,{data: PostHookSlackBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postHookSlack>>, TError,{data: PostHookSlackBody}, TContext> => {

const mutationKey = ['postHookSlack'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postHookSlack>>, {data: PostHookSlackBody}> = (props) => {
          const {data} = props ?? {};

          return  postHookSlack(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostHookSlackMutationResult = NonNullable<Awaited<ReturnType<typeof postHookSlack>>>
    export type PostHookSlackMutationBody = PostHookSlackBody
    export type PostHookSlackMutationError = ErrorResponse

    export const usePostHookSlack = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postHookSlack>>, TError,{data: PostHookSlackBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postHookSlack>>,
        TError,
        {data: PostHookSlackBody},
        TContext
      > => {
      return useMutation(getPostHookSlackMutationOptions(options), queryClient);
    }

export type getAuthOidcLoginResponse302 = {
  data: void
  status: 302
}

export type getAuthOidcLoginResponse500 = {
  data: ErrorResponse
  status: 500
}

;
export type getAuthOidcLoginResponseError = (getAuthOidcLoginResponse302 | getAuthOidcLoginResponse500) & {
  headers: Headers;
};

export type getAuthOidcLoginResponse = (getAuthOidcLoginResponseError)

export const getGetAuthOidcLoginUrl = () => {




  return `http://localhost:65080/api/v1/auth/oidc/login`
}

export const getAuthOidcLogin = async ( options?: RequestInit): Promise<getAuthOidcLoginResponse> => {

  return customInstance<getAuthOidcLoginResponse>(getGetAuthOidcLoginUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthOidcLoginQueryKey = () => {
    return [
    `http://localhost:65080/api/v1/auth/oidc/login`
    ] as const;
    }


export const getGetAuthOidcLoginQueryOptions = <TData = Awaited<ReturnType<typeof getAuthOidcLogin>>, TError = void | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcLogin>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthOidcLoginQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthOidcLogin>>> = ({ signal }) => getAuthOidcLogin({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthOidcLoginQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthOidcLogin>>>
export type GetAuthOidcLoginQueryError = void | ErrorResponse


export function useGetAuthOidcLogin<TData = Awaited<ReturnType<typeof getAuthOidcLogin>>, TError = void | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOidcLogin>>,
          TError,
          Awaited<ReturnType<typeof getAuthOidcLogin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthOidcLogin<TData = Awaited<ReturnType<typeof getAuthOidcLogin>>, TError = void | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOidcLogin>>,
          TError,
          Awaited<ReturnType<typeof getAuthOidcLogin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthOidcLogin<TData = Awaited<ReturnType<typeof getAuthOidcLogin>>, TError = void | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcLogin>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAuthOidcLogin<TData = Awaited<ReturnType<typeof getAuthOidcLogin>>, TError = void | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcLogin>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthOidcLoginQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getAuthOidcCallbackResponse302 = {
  data: void
  status: 302
}

export type getAuthOidcCallbackResponse500 = {
  data: ErrorResponse
  status: 500
}

;
export type getAuthOidcCallbackResponseError = (getAuthOidcCallbackResponse302 | getAuthOidcCallbackResponse500) & {
  headers: Headers;
};

export type getAuthOidcCallbackResponse = (getAuthOidcCallbackResponseError)

export const getGetAuthOidcCallbackUrl = (params: GetAuthOidcCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:65080/api/v1/auth/oidc/callback?${stringifiedParams}` : `http://localhost:65080/api/v1/auth/oidc/callback`
}

export const getAuthOidcCallback = async (params: GetAuthOidcCallbackParams, options?: RequestInit): Promise<getAuthOidcCallbackResponse> => {

  return customInstance<getAuthOidcCallbackResponse>(getGetAuthOidcCallbackUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthOidcCallbackQueryKey = (params?: GetAuthOidcCallbackParams,) => {
    return [
    `http://localhost:65080/api/v1/auth/oidc/callback`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAuthOidcCallbackQueryOptions = <TData = Awaited<ReturnType<typeof getAuthOidcCallback>>, TError = void | ErrorResponse>(params: GetAuthOidcCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthOidcCallbackQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthOidcCallback>>> = ({ signal }) => getAuthOidcCallback(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthOidcCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthOidcCallback>>>
export type GetAuthOidcCallbackQueryError = void | ErrorResponse


export function useGetAuthOidcCallback<TData = Awaited<ReturnType<typeof getAuthOidcCallback>>, TError = void | ErrorResponse>(
 params: GetAuthOidcCallbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOidcCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthOidcCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthOidcCallback<TData = Awaited<ReturnType<typeof getAuthOidcCallback>>, TError = void | ErrorResponse>(
 params: GetAuthOidcCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOidcCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthOidcCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthOidcCallback<TData = Awaited<ReturnType<typeof getAuthOidcCallback>>, TError = void | ErrorResponse>(
 params: GetAuthOidcCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAuthOidcCallback<TData = Awaited<ReturnType<typeof getAuthOidcCallback>>, TError = void | ErrorResponse>(
 params: GetAuthOidcCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthOidcCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthOidcCallbackQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type postAuthLoginResponse200 = {
  data: void
  status: 200
}

export type postAuthLoginResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
export type postAuthLoginResponseError = (postAuthLoginResponse500) & {
  headers: Headers;
};

export type postAuthLoginResponse = (postAuthLoginResponseSuccess | postAuthLoginResponseError)

export const getPostAuthLoginUrl = () => {




  return `http://localhost:65080/api/v1/auth/login`
}

export const postAuthLogin = async (adminCreateRequest: AdminCreateRequest, options?: RequestInit): Promise<postAuthLoginResponse> => {

  return customInstance<postAuthLoginResponse>(getPostAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminCreateRequest)
  }
);}




export const getPostAuthLoginMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: AdminCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: AdminCreateRequest}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: AdminCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = AdminCreateRequest
    export type PostAuthLoginMutationError = ErrorResponse

    export const usePostAuthLogin = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: AdminCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: AdminCreateRequest},
        TContext
      > => {
      return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
    }

export type postAuthLogoutResponse302 = {
  data: void
  status: 302
}

export type postAuthLogoutResponse500 = {
  data: ErrorResponse
  status: 500
}

;
export type postAuthLogoutResponseError = (postAuthLogoutResponse302 | postAuthLogoutResponse500) & {
  headers: Headers;
};

export type postAuthLogoutResponse = (postAuthLogoutResponseError)

export const getPostAuthLogoutUrl = () => {




  return `http://localhost:65080/api/v1/auth/logout`
}

export const postAuthLogout = async ( options?: RequestInit): Promise<postAuthLogoutResponse> => {

  return customInstance<postAuthLogoutResponse>(getPostAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostAuthLogoutMutationOptions = <TError = void | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {


          return  postAuthLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>

    export type PostAuthLogoutMutationError = void | ErrorResponse

    export const usePostAuthLogout = <TError = void | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthLogoutMutationOptions(options), queryClient);
    }

export type getAuthMeResponse200 = {
  data: UserResponse
  status: 200
}

export type getAuthMeResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAuthMeResponseSuccess = (getAuthMeResponse200) & {
  headers: Headers;
};
export type getAuthMeResponseError = (getAuthMeResponse500) & {
  headers: Headers;
};

export type getAuthMeResponse = (getAuthMeResponseSuccess | getAuthMeResponseError)

export const getGetAuthMeUrl = () => {




  return `http://localhost:65080/api/v1/auth/me`
}

export const getAuthMe = async ( options?: RequestInit): Promise<getAuthMeResponse> => {

  return customInstance<getAuthMeResponse>(getGetAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthMeQueryKey = () => {
    return [
    `http://localhost:65080/api/v1/auth/me`
    ] as const;
    }


export const getGetAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getAuthMe>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({ signal }) => getAuthMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthMe>>>
export type GetAuthMeQueryError = ErrorResponse


export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getAdminResponse200 = {
  data: AdminGetResponse
  status: 200
}

export type getAdminResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAdminResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAdminResponseSuccess = (getAdminResponse200) & {
  headers: Headers;
};
export type getAdminResponseError = (getAdminResponse404 | getAdminResponse500) & {
  headers: Headers;
};

export type getAdminResponse = (getAdminResponseSuccess | getAdminResponseError)

export const getGetAdminUrl = () => {




  return `http://localhost:65080/api/v1/admin`
}

export const getAdmin = async ( options?: RequestInit): Promise<getAdminResponse> => {

  return customInstance<getAdminResponse>(getGetAdminUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminQueryKey = () => {
    return [
    `http://localhost:65080/api/v1/admin`
    ] as const;
    }


export const getGetAdminQueryOptions = <TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdmin>>> = ({ signal }) => getAdmin({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminQueryResult = NonNullable<Awaited<ReturnType<typeof getAdmin>>>
export type GetAdminQueryError = ErrorResponse


export function useGetAdmin<TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdmin>>,
          TError,
          Awaited<ReturnType<typeof getAdmin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdmin<TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdmin>>,
          TError,
          Awaited<ReturnType<typeof getAdmin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdmin<TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAdmin<TData = Awaited<ReturnType<typeof getAdmin>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdmin>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type postAdminResponse201 = {
  data: void
  status: 201
}

export type postAdminResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postAdminResponseSuccess = (postAdminResponse201) & {
  headers: Headers;
};
export type postAdminResponseError = (postAdminResponse500) & {
  headers: Headers;
};

export type postAdminResponse = (postAdminResponseSuccess | postAdminResponseError)

export const getPostAdminUrl = () => {




  return `http://localhost:65080/api/v1/admin`
}

export const postAdmin = async (adminCreateRequest: AdminCreateRequest, options?: RequestInit): Promise<postAdminResponse> => {

  return customInstance<postAdminResponse>(getPostAdminUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminCreateRequest)
  }
);}




export const getPostAdminMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdmin>>, TError,{data: AdminCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdmin>>, TError,{data: AdminCreateRequest}, TContext> => {

const mutationKey = ['postAdmin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdmin>>, {data: AdminCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAdmin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminMutationResult = NonNullable<Awaited<ReturnType<typeof postAdmin>>>
    export type PostAdminMutationBody = AdminCreateRequest
    export type PostAdminMutationError = ErrorResponse

    export const usePostAdmin = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdmin>>, TError,{data: AdminCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdmin>>,
        TError,
        {data: AdminCreateRequest},
        TContext
      > => {
      return useMutation(getPostAdminMutationOptions(options), queryClient);
    }

export type getAuditlogResponse200 = {
  data: AuditlogGetResponse
  status: 200
}

export type getAuditlogResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAuditlogResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAuditlogResponseSuccess = (getAuditlogResponse200) & {
  headers: Headers;
};
export type getAuditlogResponseError = (getAuditlogResponse404 | getAuditlogResponse500) & {
  headers: Headers;
};

export type getAuditlogResponse = (getAuditlogResponseSuccess | getAuditlogResponseError)

export const getGetAuditlogUrl = (params: GetAuditlogParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:65080/api/v1/auditlog?${stringifiedParams}` : `http://localhost:65080/api/v1/auditlog`
}

export const getAuditlog = async (params: GetAuditlogParams, options?: RequestInit): Promise<getAuditlogResponse> => {

  return customInstance<getAuditlogResponse>(getGetAuditlogUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuditlogQueryKey = (params?: GetAuditlogParams,) => {
    return [
    `http://localhost:65080/api/v1/auditlog`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAuditlogQueryOptions = <TData = Awaited<ReturnType<typeof getAuditlog>>, TError = ErrorResponse>(params: GetAuditlogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditlog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuditlogQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuditlog>>> = ({ signal }) => getAuditlog(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuditlog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuditlogQueryResult = NonNullable<Awaited<ReturnType<typeof getAuditlog>>>
export type GetAuditlogQueryError = ErrorResponse


export function useGetAuditlog<TData = Awaited<ReturnType<typeof getAuditlog>>, TError = ErrorResponse>(
 params: GetAuditlogParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditlog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuditlog>>,
          TError,
          Awaited<ReturnType<typeof getAuditlog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuditlog<TData = Awaited<ReturnType<typeof getAuditlog>>, TError = ErrorResponse>(
 params: GetAuditlogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditlog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuditlog>>,
          TError,
          Awaited<ReturnType<typeof getAuditlog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuditlog<TData = Awaited<ReturnType<typeof getAuditlog>>, TError = ErrorResponse>(
 params: GetAuditlogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditlog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAuditlog<TData = Awaited<ReturnType<typeof getAuditlog>>, TError = ErrorResponse>(
 params: GetAuditlogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditlog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuditlogQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
