#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";
    CREATE DATABASE inngest OWNER komik;
    GRANT ALL PRIVILEGES ON DATABASE komik TO komik;
    GRANT ALL PRIVILEGES ON DATABASE inngest TO komik;
EOSQL
