// Package apidefn provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apidefn

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// DetailedAgentModel defines model for DetailedAgentModel.
type DetailedAgentModel struct {
	AgentID     *openapi_types.UUID `json:"agentID,omitempty"`
	Annotations *[]struct {
		Name  string `json:"name"`
		Value string `json:"value"`
	} `json:"annotations,omitempty"`
	Description *string `json:"description,omitempty"`
	Env         *[]struct {
		Name  string `json:"name"`
		Value string `json:"value"`
	} `json:"env,omitempty"`
	Image           string                       `json:"image"`
	ImagePullSecret *string                      `json:"imagePullSecret,omitempty"`
	Name            string                       `json:"name"`
	Resources       *AgentCreateRequestResources `json:"resources,omitempty"`
	Secrets         *[]struct {
		Name  string `json:"name"`
		Value string `json:"value"`
	} `json:"secrets,omitempty"`
}

// AdminCreateRequest defines model for adminCreateRequest.
type AdminCreateRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AdminGetResponse defines model for adminGetResponse.
type AdminGetResponse struct {
	Exists bool `json:"exists"`
}

// AgentCreateRequest defines model for agentCreateRequest.
type AgentCreateRequest struct {
	Annotations *[]struct {
		Name  string `json:"name"`
		Value string `json:"value"`
	} `json:"annotations,omitempty"`
	Description *string `json:"description,omitempty"`
	Env         *[]struct {
		Name  string `json:"name"`
		Value string `json:"value"`
	} `json:"env,omitempty"`
	Image           string                       `json:"image"`
	ImagePullSecret *string                      `json:"imagePullSecret,omitempty"`
	Name            string                       `json:"name"`
	Resources       *AgentCreateRequestResources `json:"resources,omitempty"`
	Secrets         *[]struct {
		Name  string `json:"name"`
		Value string `json:"value"`
	} `json:"secrets,omitempty"`
}

// AgentCreateRequestResources defines model for agentCreateRequestResources.
type AgentCreateRequestResources struct {
	Cpu              *string `json:"cpu,omitempty"`
	EphemeralStorage *string `json:"ephemeralStorage,omitempty"`
	Memory           *string `json:"memory,omitempty"`
	TimeoutSeconds   *int    `json:"timeoutSeconds,omitempty"`
}

// AgentCreateResponse defines model for agentCreateResponse.
type AgentCreateResponse struct {
	AgentID openapi_types.UUID `json:"agentID"`
	Name    string             `json:"name"`
}

// AgentGetResponse defines model for agentGetResponse.
type AgentGetResponse struct {
	Agents *[]AgentModel `json:"agents,omitempty"`
}

// AgentModel defines model for agentModel.
type AgentModel struct {
	AgentID *openapi_types.UUID `json:"agentID,omitempty"`
	Name    *string             `json:"name,omitempty"`
}

// AuditlogGetResponse defines model for auditlogGetResponse.
type AuditlogGetResponse struct {
	Items    *[]AuditlogResponse `json:"items,omitempty"`
	Metadata *struct {
		Limit  *int `json:"limit,omitempty"`
		Offset *int `json:"offset,omitempty"`
		Total  *int `json:"total,omitempty"`
	} `json:"metadata,omitempty"`
}

// AuditlogResponse defines model for auditlogResponse.
type AuditlogResponse struct {
	CorrelationId *string             `json:"correlation_id,omitempty"`
	Data          *string             `json:"data,omitempty"`
	EventId       *openapi_types.UUID `json:"event_id,omitempty"`
	EventType     *string             `json:"event_type,omitempty"`
	EventVersion  *int                `json:"event_version,omitempty"`
	InitiatorId   *string             `json:"initiator_id,omitempty"`
	InitiatorType *string             `json:"initiator_type,omitempty"`
	OccurredAt    *time.Time          `json:"occurred_at,omitempty"`
	ResourceType  *string             `json:"resource_type,omitempty"`
	Severity      *string             `json:"severity,omitempty"`
}

// ErrorResponse defines model for errorResponse.
type ErrorResponse struct {
	ErrorCode    *string `json:"error_code,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
}

// UserResponse defines model for userResponse.
type UserResponse struct {
	Id       *openapi_types.UUID  `json:"id,omitempty"`
	Username *openapi_types.Email `json:"username,omitempty"`
}

// GetAuditlogParams defines parameters for GetAuditlog.
type GetAuditlogParams struct {
	Limit  int `form:"limit" json:"limit"`
	Offset int `form:"offset" json:"offset"`
}

// GetAuthOidcCallbackParams defines parameters for GetAuthOidcCallback.
type GetAuthOidcCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// PostHookSlackJSONBody defines parameters for PostHookSlack.
type PostHookSlackJSONBody map[string]interface{}

// PostAdminJSONRequestBody defines body for PostAdmin for application/json ContentType.
type PostAdminJSONRequestBody = AdminCreateRequest

// PostAgentJSONRequestBody defines body for PostAgent for application/json ContentType.
type PostAgentJSONRequestBody = AgentCreateRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AdminCreateRequest

// PostHookSlackJSONRequestBody defines body for PostHookSlack for application/json ContentType.
type PostHookSlackJSONRequestBody PostHookSlackJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin)
	GetAdmin(ctx *echo.Context) error

	// (POST /admin)
	PostAdmin(ctx *echo.Context) error

	// (GET /agent)
	GetAgent(ctx *echo.Context) error

	// (POST /agent)
	PostAgent(ctx *echo.Context) error

	// (GET /agent/{id})
	GetAgentId(ctx *echo.Context, id openapi_types.UUID) error

	// (GET /auditlog)
	GetAuditlog(ctx *echo.Context, params GetAuditlogParams) error

	// (POST /auth/login)
	PostAuthLogin(ctx *echo.Context) error

	// (POST /auth/logout)
	PostAuthLogout(ctx *echo.Context) error

	// (GET /auth/me)
	GetAuthMe(ctx *echo.Context) error

	// (GET /auth/oidc/callback)
	GetAuthOidcCallback(ctx *echo.Context, params GetAuthOidcCallbackParams) error

	// (GET /auth/oidc/login)
	GetAuthOidcLogin(ctx *echo.Context) error

	// (POST /hook/slack)
	PostHookSlack(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdmin(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdmin(ctx)
	return err
}

// PostAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAdmin(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAdmin(ctx)
	return err
}

// GetAgent converts echo context to params.
func (w *ServerInterfaceWrapper) GetAgent(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAgent(ctx)
	return err
}

// PostAgent converts echo context to params.
func (w *ServerInterfaceWrapper) PostAgent(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAgent(ctx)
	return err
}

// GetAgentId converts echo context to params.
func (w *ServerInterfaceWrapper) GetAgentId(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAgentId(ctx, id)
	return err
}

// GetAuditlog converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuditlog(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuditlogParams
	// ------------- Required query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Required query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuditlog(ctx, params)
	return err
}

// PostAuthLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogin(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogin(ctx)
	return err
}

// PostAuthLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogout(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogout(ctx)
	return err
}

// GetAuthMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthMe(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthMe(ctx)
	return err
}

// GetAuthOidcCallback converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthOidcCallback(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthOidcCallbackParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", ctx.QueryParams(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", ctx.QueryParams(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthOidcCallback(ctx, params)
	return err
}

// GetAuthOidcLogin converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthOidcLogin(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthOidcLogin(ctx)
	return err
}

// PostHookSlack converts echo context to params.
func (w *ServerInterfaceWrapper) PostHookSlack(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostHookSlack(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/admin", wrapper.GetAdmin, options.OperationMiddlewares["GetAdmin"]...)
	router.POST(options.BaseURL+"/admin", wrapper.PostAdmin, options.OperationMiddlewares["PostAdmin"]...)
	router.GET(options.BaseURL+"/agent", wrapper.GetAgent, options.OperationMiddlewares["GetAgent"]...)
	router.POST(options.BaseURL+"/agent", wrapper.PostAgent, options.OperationMiddlewares["PostAgent"]...)
	router.GET(options.BaseURL+"/agent/:id", wrapper.GetAgentId, options.OperationMiddlewares["GetAgentId"]...)
	router.GET(options.BaseURL+"/auditlog", wrapper.GetAuditlog, options.OperationMiddlewares["GetAuditlog"]...)
	router.POST(options.BaseURL+"/auth/login", wrapper.PostAuthLogin, options.OperationMiddlewares["PostAuthLogin"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout, options.OperationMiddlewares["PostAuthLogout"]...)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetAuthMe, options.OperationMiddlewares["GetAuthMe"]...)
	router.GET(options.BaseURL+"/auth/oidc/callback", wrapper.GetAuthOidcCallback, options.OperationMiddlewares["GetAuthOidcCallback"]...)
	router.GET(options.BaseURL+"/auth/oidc/login", wrapper.GetAuthOidcLogin, options.OperationMiddlewares["GetAuthOidcLogin"]...)
	router.POST(options.BaseURL+"/hook/slack", wrapper.PostHookSlack, options.OperationMiddlewares["PostHookSlack"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FlLb9u4E/8qBv//o2rZSdODbt0Wmw3abILkWAQBI45tNhSpkCPvGoa++4Kk/JBFPbKIAXeRU2RyHpyZ",
	"3zzIrEmqslxJkGhIsiYmXUBG3edXQMoFsM9zkHitGAi7SoW4mZHkx5r8X8OMJOR/8U5CXLHHdMdTRgNI",
	"v2igCHfwUoBBUj5EBFc5kISop5+QIikjQlnGZZ0uWZNcqxw0cnBHzqkxfynN7PdM6YwiSXaLW6EGNZdz",
	"K7QwoCXNwDIcbJYR0fBScA2MJD92lNFOYOsxLwHvwORKGmgeEv7mxju7Yn5SSgCVDZUVYVBL02kNPVRK",
	"hRS5ku4nR8hMk6rF+ogsqSgG+KXyiacOHbVaoFrTlf3NwKSa5/ZcQb0gl6d0XJ7ROfiw0SwXdm++SPWY",
	"q/hZZfxZ0Cf/4UKSLKchmDkht4UQ95BqwLq4bPXB+OUAZ6u9GowqdOq98rr8utuylhHxqk8IIWFuH4Zh",
	"qXC375q6LWle1J1/MT3LQn6HfAEZaCruUekGAqaXPMSUQab0qk56dvHpOkiMPANV4D2kSjJTYzr/NJls",
	"ObhEmIN2juk2vq3gOKKrr7WiWBScvQJvB0HZSKzoW8PSWQcdRR14g1tKEzPhA2zb1jE80lRZMI5CzTvN",
	"3ho7zOpK5FZeoERlgJRRpE1dgme8Xm3OLprAioiazcxBWZqE6FAhFTWy6TCkdnmr3VWp0hqEa2GPnAVr",
	"0MbuZgIvQWLF1RtjT+yXW2UtQZt609rzDJccOUWl2w66I2hVo9K00BrYI8XaqRlF+GDLRejomz7QLtbA",
	"EjTH1UAQg9ZKd0wvdvsxVazFVW47A2OqojlAox2tOvJlWAj3J7ktMWSUiyZ1AJ8uQjPlTszRVe7Pt1ej",
	"L0qipima0Uzp0Tfb520r2yCBTMcTF7kcJM05Scj5eDI+dzMiLtzxYzcQ2q+5zzBrm4P0FSMJuQT87Ahc",
	"JJ0LHNvZZOIzQCJIx0fzXPDUccY/jcehrxK9NeRwJHXm1uYwcvPN2vFx8vHNtNZxFFD5p8LR76qQzGq+",
	"eEN7ezXbvNWSipEBvQQ9cgweFnRuXINzMXkoI5IrEwjbrTJ7cXNTx2+Krd42ZAeXonoTRl1A2QDN1P6p",
	"G+ulnLKTy4j47t6ZJY7gmFlyOLC8Z0lvAF1MerJkG7cjZEng6WBIlkyOc4I+3Jxo9LbpF685K3tz8Iq5",
	"9qZpBgjauKcg2+Bcy9vcCBLiunQ9ENGebT39vHw4YtACD1vvuf4qtFSTeydWNjRhsLwUoFc7tPiLShdg",
	"Om8wZRQWW91rBskN3WOOicLQZfEdhr0w3MBqg0RcxELN/YTd0YUKXHx3ZKc1r02a89pp9ooCFwcuVwUO",
	"8rmlO7D7fHLWtPt0EVc33V8x28seLq7hmHNq7bb8y8waB05UnKVxSoV4oulznz9vOEu/bGgHtRP3PNFV",
	"9RsPAmE5Bim+TtDDfwnqLkrb6toXol19HWZ/RBZAmQvjmnxX3ui6vYfeLU/aZwulnmMjKkS3F8Y/lHq+",
	"Fx7M/7YZUca43aLidu+1zKMz8Lb1tjeiRlh+iRpkw2Mj5Z5ELY2vH4UWJCELxNwkcUxzPva7YwSD8XLq",
	"/xvtZWz+GVY9XdiysVmwMNj77ZTV9qu5ZX/NjdTlQ/lPAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
