// Package apidefn provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apidefn

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AdminCreateRequest defines model for adminCreateRequest.
type AdminCreateRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AdminGetResponse defines model for adminGetResponse.
type AdminGetResponse struct {
	Exists bool `json:"exists"`
}

// ErrorResponse defines model for errorResponse.
type ErrorResponse struct {
	ErrorCode    *string `json:"error_code,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
}

// UserResponse defines model for userResponse.
type UserResponse struct {
	Id       *openapi_types.UUID  `json:"id,omitempty"`
	Username *openapi_types.Email `json:"username,omitempty"`
}

// GetAuthOidcCallbackParams defines parameters for GetAuthOidcCallback.
type GetAuthOidcCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// PostHookSlackJSONBody defines parameters for PostHookSlack.
type PostHookSlackJSONBody map[string]interface{}

// PostAdminJSONRequestBody defines body for PostAdmin for application/json ContentType.
type PostAdminJSONRequestBody = AdminCreateRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AdminCreateRequest

// PostHookSlackJSONRequestBody defines body for PostHookSlack for application/json ContentType.
type PostHookSlackJSONRequestBody PostHookSlackJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin)
	GetAdmin(ctx *echo.Context) error

	// (POST /admin)
	PostAdmin(ctx *echo.Context) error

	// (POST /auth/login)
	PostAuthLogin(ctx *echo.Context) error

	// (POST /auth/logout)
	PostAuthLogout(ctx *echo.Context) error

	// (GET /auth/me)
	GetAuthMe(ctx *echo.Context) error

	// (GET /auth/oidc/callback)
	GetAuthOidcCallback(ctx *echo.Context, params GetAuthOidcCallbackParams) error

	// (GET /auth/oidc/login)
	GetAuthOidcLogin(ctx *echo.Context) error

	// (POST /hook/slack)
	PostHookSlack(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdmin(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdmin(ctx)
	return err
}

// PostAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAdmin(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAdmin(ctx)
	return err
}

// PostAuthLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogin(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogin(ctx)
	return err
}

// PostAuthLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogout(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogout(ctx)
	return err
}

// GetAuthMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthMe(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthMe(ctx)
	return err
}

// GetAuthOidcCallback converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthOidcCallback(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthOidcCallbackParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", ctx.QueryParams(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", ctx.QueryParams(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthOidcCallback(ctx, params)
	return err
}

// GetAuthOidcLogin converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthOidcLogin(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthOidcLogin(ctx)
	return err
}

// PostHookSlack converts echo context to params.
func (w *ServerInterfaceWrapper) PostHookSlack(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostHookSlack(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/admin", wrapper.GetAdmin, options.OperationMiddlewares["GetAdmin"]...)
	router.POST(options.BaseURL+"/admin", wrapper.PostAdmin, options.OperationMiddlewares["PostAdmin"]...)
	router.POST(options.BaseURL+"/auth/login", wrapper.PostAuthLogin, options.OperationMiddlewares["PostAuthLogin"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout, options.OperationMiddlewares["PostAuthLogout"]...)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetAuthMe, options.OperationMiddlewares["GetAuthMe"]...)
	router.GET(options.BaseURL+"/auth/oidc/callback", wrapper.GetAuthOidcCallback, options.OperationMiddlewares["GetAuthOidcCallback"]...)
	router.GET(options.BaseURL+"/auth/oidc/login", wrapper.GetAuthOidcLogin, options.OperationMiddlewares["GetAuthOidcLogin"]...)
	router.POST(options.BaseURL+"/hook/slack", wrapper.PostHookSlack, options.OperationMiddlewares["PostHookSlack"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FZNb9swDP0rAbejEacfu/jWFVhXtFuL7jgEhWozsRpbdCWqWxH4vw+U0ubDSZMNHZDtFEeiSL3HR1JT",
	"yKluyKBhB9kUXF5ircKnKmptTi0qxht88OhYVhtLDVrWGGwa5dwPsoV8j8jWiiGbLybATw1CBo6tNmNo",
	"E/AOrVE1yoGVzTYBiw9eWywg+z63TOYOhy8e6e4ecxaP4ZpnyDfoGjIOu5fEn9pFdLPDd0QVKtMJOTNc",
	"FwWtJftKCNm+zalYB2x2+rZG59R4A/RORMG/OaBeptx7vZXuF2Osla661t1LyJI2Iwo31lzJ3sn1ee+U",
	"DFuVs+uNyPYuqNYTSOARrdNkIIOD/kCCU4NGNRoyOOoP+kchkVyG66cha/I1xiArwaZYkzkvIIMz5JNg",
	"IPmJFIRjh4OB/ORkGE04p5qm0nk4md47MnMNy9d7iyPI4F06F3k6U3ja0U2AW6DLrW44Arm6EBzHg+M3",
	"i7qsozUhvxL3PpE3hUT+8IZ4t0bWhkUsVc+hfUTbCweiLNTYSX3EpA3bBBpya9J2TW4hb6FlfKTi6W1T",
	"ttyR2uUaZuux7YjmQH6WwUYv+0xym0CqPJdpReNYKq+Q7rm8DGb7RfygS3wsqX3j3HO5Qjl53olzsVvB",
	"fTQ47OLe25pegR5nxcau7Ln8gn+zLS+NvY0tec9JJF3kaa6q6k7lk218XukiP322lRlpVY2MVjxPQUof",
	"HjzaJ0ggjnII74zV6ksW4HYm+3o/jhX/nqPh/yT1kKWX7rotRfP+uhv+BEpURUjjFC4pgl7Gu8puu9ec",
	"lUST1FUzRW9ujJ+JJt+qKOY/HUaqKLRsqep64dkb1bnmkbrTHNo5eCct/0QPkvRIptoEok3sH95WkEHJ",
	"3LgsTVWj+3G3z+g4fTwAqemZj+lzY4hvEGkbzwsig4X/IVg7bH8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
